spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to MyBank accounts related prod APIs "
  contactDetails:
    name: "Mithil Bhosale - Product Owner"
    email: "mb@google.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384