spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to MyBank loans related QA APIs "
  contactDetails:
    name: "Mithil Bhosale - QA Lead"
    email: "mb@preparationzone.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467