spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to MyBank loans related prod APIs "
  contactDetails:
    name: "Kishor Bhosale - Product Owner"
    email: "kb@preparationzone.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956