spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to MyBank cards related QA APIs "
  contactDetails:
    name: "Kishor Bhosale - QA Lead"
    email: "kb@preparationzone.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267