spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EMyBank cards related prod APIs "
  contactDetails:
    name: "Mithil Bhosale - Product Owner"
    email: "mb@google.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721